'use client';
import { state } from 'react';


import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link';
import Image from 'next/image';
import logo from '../../public/next.svg';
import Topo from "../components/Topo";
import Rodape from "../components/Rodape";
import Card from "@/components/Card";
import Botao from "@/components/ex1/Botao";
import Switch from "@/components/ex2/Switch";
import GeradorAleatorio from "@/components/ex3/GeradorAleatorio";
import NovoSwitch from "@/components/ex4/NovoSwitch";


export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Topo/>
      <section className={styles.container}>
      {/*<Card/> */}
      {/*<Card/> */}
      {/*<Card/> */}
        <Botao/>
        <Switch/>
        <GeradorAleatorio/>
        <NovoSwitch/>
      </section>
        <Rodape/>
      </main>
    </>
  );
}
